Creation of Array (1D,2D and Multidimensional Array)

In [3]:
#Exp no. : 05

In [7]:
#Aim : Creation Of Array (1D,2D and Multidimensional Array) using numpy

In [9]:
#Name : Taufiq Rafik Nagori
#Roll no. : 77 (DS-B77)
#Section : B 
#Subject : PE-I
#Date : 03/08/24

In [11]:
import numpy as np

In [13]:
arr1=np.array([10,20,30,40,50])

In [15]:
arr1

array([10, 20, 30, 40, 50])

In [17]:
arr2=np.array([[[10,20,30,40,50],[60,70,80,90,100]]])

In [19]:
arr2

array([[[ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100]]])

In [21]:
arr3=np.array([[10,20,30,40,50],[60,70,80,90,100],[15,25,35,45,55]])

In [23]:
arr3

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [ 15,  25,  35,  45,  55]])